FROM golang:1.17 as builder

WORKDIR /app
COPY . .
RUN export GOPROXY=https://goproxy.cn,direct && go build 

FROM alpine:latest
#RUN echo "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.8/main" > /etc/apk/repositories
#RUN apk add --update curl bash && rm -rf /var/cache/apk/*
WORKDIR /work
COPY --from=builder /app/server /work
COPY entrypoint.sh /work
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
EXPOSE 8080
ENTRYPOINT ["/work/entrypoint.sh"]